# ── zap ───────────────────────────────────────────────────────────────────────

[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"

plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-completions"
plug "MichaelAquilina/zsh-you-should-use"

autoload -Uz compinit && compinit

# ── prompt ────────────────────────────────────────────────────────────────────

eval "$(starship init zsh)"

# ── tools ─────────────────────────────────────────────────────────────────────

# zoxide — smart cd, responds to `cd` directly
eval "$(zoxide init zsh --cmd cd)"

# fnm — Node version manager
eval "$(fnm env --use-on-cd --version-file-strategy=recursive)"

# ── keybindings ───────────────────────────────────────────────────────────────

# Use emacs-style editing to prevent ESC from entering vi command mode.
bindkey -e

# Word boundaries stop at every non-alphanumeric (matches macOS text editing)
WORDCHARS=''

# Arrow key history search: only match commands starting with what you've typed
# (default macOS behavior is up-line-or-search which matches anywhere in the command)
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[OA" up-line-or-beginning-search     # Up arrow
bindkey "^[OB" down-line-or-beginning-search   # Down arrow
bindkey "^[[A" up-line-or-beginning-search     # Alternative up code
bindkey "^[[B" down-line-or-beginning-search   # Alternative down code

# Option+Left/Right word navigation across terminal escape variants.
bindkey "^[b" backward-word
bindkey "^[f" forward-word
bindkey "^[[1;3D" backward-word
bindkey "^[[1;3C" forward-word
# ── history options ───────────────────────────────────────────────────────────────

HISTSIZE=1000
SAVEHIST=1000

# Clean up duplicates
setopt HIST_FIND_NO_DUPS         # Don't show duplicates when searching
setopt HIST_IGNORE_DUPS          # Don't save if it matches the previous entry
setopt HIST_IGNORE_ALL_DUPS      # Remove older duplicate when new one is entered
setopt HIST_SAVE_NO_DUPS         # Don't save duplicate when writing file

setopt HIST_EXPIRE_DUPS_FIRST    # When full, drop duplicates before unique entries

# Clean commands we don't want
setopt HIST_IGNORE_SPACE         # Don't save if command starts with space
setopt HIST_NO_FUNCTIONS         # Don't save function definitions
setopt HIST_REDUCE_BLANKS        # Remove blank lines from history

# Write & share history
setopt INC_APPEND_HISTORY        # Write to history immediately
setopt SHARE_HISTORY             # Share history between terminals

# ── aliases: shell ───────────────────────────────────────────────────────────

alias ls='eza -la'
alias cat='bat --plain'
alias find='fd'
alias grep='rg'
alias brewup='brew update && brew upgrade && brew cleanup'

# ── aliases: git ─────────────────────────────────────────────────────────────

alias ga='git add --all'
alias gc='git commit -m'
alias gca='git commit --amend --no-edit'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gst='git status'
alias gsta='git stash'
alias gstp='git stash pop'
alias gstl='git stash list'
alias glo='git log --oneline --graph --decorate --all'
alias gundo='git reset --soft HEAD~1'

gsw() { git switch "$1" 2>/dev/null || git switch -c "$1"; }

# ── gh: auto-switch account based on cwd ─────────────────────────────────────
# Reads ~/.config/gh/dir-mapping (generated by bootstrap) to resolve the
# gh account for the current directory. Format: /path/<tab>gh-username

gh() {
  local mapfile="$HOME/.config/gh/dir-mapping"
  if [[ -f "$mapfile" ]]; then
    local cwd="$PWD/" dir user
    while IFS=$'\t' read -r dir user; do
      if [[ "$cwd" == "$dir"* ]]; then
        local active
        active=$(command gh auth status 2>&1 | awk '/Active account: true/{getline; print}' | grep -o 'account [^ ]*' | cut -d' ' -f2)
        if [[ "$active" != "$user" ]]; then
          command gh auth switch --user "$user" 2>/dev/null
        fi
        break
      fi
    done < "$mapfile"
  fi
  command gh "$@"
}
